import { StringBank } from './bank';

export const ar: Record<StringBank, string> = {
  ADD_NEW_CATEGORY: 'فئة جديدة',
  ADD_RATIONALE_HEADER: 'اضافة:',
  ADD_RATIONALE_PARAGRAPH: `لماذا تستلزم هذه الاتفاقية؟ ما الخلفية من وراء انشاءها؟ أي احتياجات او مشاكل قد تحل؟`,
  AGREEMENT_NAME_FIELD: 'اسم الاتفاقية',
  AGREEMENT_PARTICIPANTS: 'مشتركين {{count}}',
  AGREEMENT_PROCESS_RULES: 'قواعد عملية الاتفاق',
  AGREEMENT_APPROVAL_RULES: 'قواعد الموافقة على الاتفاقية',
  AGREEMENT_APPROVAL_RULES_DESCRIPTION: 'عين قواعد لتغيير حالة الاتفاقية الى "متفق عليها"',
  AGREEMENT_PROCESS_RULES_DESCRIPTION:
    'عيّن قواعد لقبول التغييرات على الاتفاقية عن طريق إضافة أقسام جديدة والموافقة عليها والموافقة على إصدارات تحسين الأقسام',
  AGREEMENT_PUBLIHSED_SUCCESSFULLY: 'تم نشر اتفاقيتك بنجاح',
  AGREEMENT_UPDATED_AT: '{{date}} :اخر حتلنة',
  ALL_AGREEMENTS: 'كل الاتفاقيات',
  ARCHIVE: 'ارشيف',
  ARCHIVE_EMPTY_MESSAGE: 'هنا ستخزن الاتفاقيات في الارشيف',
  ARCHIVE_EMPTY_MESSAGE_END: 'إذا كانت موجودة',
  BACK: 'رجوع',
  CATEGORY: 'فئة',
  CATEGORIES: 'فئات',
  CATEGORY_EMPTY_MESSAGE: 'هل تريد انشاء مجموعة جديدة؟',
  COMING_SOON: 'قريباً',
  CONTINUE: 'أكمل',
  CREATE_FIRST_AGREEMENT: 'حرر اتفاقيتك الاولى',
  GOTO_HOMEPAGE_TITLE: 'الى صفحة البيت',
  GROUP_AGREEMENTS: '{{group}}:عدد الاتفاقيات في مجموعة',
  CATEGORY_AGREMENTS: '{{category}} الاتفاقيات الفعالة - فئة',
  INSERT_NEW_SECTION: ' (Ctrl/Cmd+Enter) أضافة فقرة جديدة +',
  LOGOUT: 'خروج',
  NEW_AGREEMENT: 'اتفاقية جديدة',
  NEW_CHAPTER: 'فقرة جديدة',
  NO_CATEGORY: 'بدون فئة',
  PUBLISH_AGREEMENT: 'نشر الاتفاقية',
  RATIONALE: 'الأساس المنطقي',
  REQUIRE_ADMIN_APPROVAL: 'يلزم موافقة المدير',
  REQUIRE_ADMIN_APPROVAL_DESCRIPTION: 'على المدير الوافقة على تغيير المسودة',
  RETURN_TO_ALL_AGREEMENTS: 'العودة الى كل الاتفاقيات',
  RULES: 'القوانين',
  SECTION_CARD_CONTENT_SECTION_NAME: '{{sectionNum}} :فقرة',
  SECTION_CARD_CONTENT_VERSIONS: '{{totalVersionsNum}} من {{versionNum}} اصدار',
  SECTION_CARD_TITLE_CHAPTER: '# {{chapterName}}',
  SECTION_CARD_TITLE_SECTIONS: 'فقرات {{sectionNum}}',
  SECTION_CARD_TITLE_VERSIONS: 'اصدارات {{versionsNum}}',
  SECTIONS: 'فقرات',
  SHARE_AGREEMENT: 'شارك هذه الاتفاقية',
  TIME_LIMITED_DESCRIPTION: 'كم من الوقت ستكون نسخة هذه الاتفاقية معروضة للتصويت؟',
  TIME_LIMITED: 'محدد بالوقت',
  UNARCHIVE: 'نقل من الارشيف',
  UNCATEGORIZED: 'عام',
  URL_COPIED_SUCCESSFULLY: 'تم نسخ الرابط بنجاح',
  VERSION: 'اصدار',
  VIEW_AGREEMENT: 'عرض الاتفاقية',
  VIEW_CURRENT_DRAFT: 'عرض المسودة الحالية',
  WELCOME_HEADER: 'مرحباً بكم في كونسنز!',
  WELCOME_PARAGRAPH: `لست عضو في المجوعة حتى الان,
   اطلب من مدير المجموعة استدعائك للانضمام
   استمتع!`,
};
