export enum StringBank {
  AGREEMENT_PARTICIPANTS = 'AGREEMENT_PARTICIPANTS',
  AGREEMENT_UPDATED_AT = 'AGREEMENT_UPDATED_AT',
  GROUP_AGREEMENTS = 'GROUP_AGREEMENTS',
  LOGOUT = 'LOGOUT',
  GOTO_HOMEPAGE_TITLE = 'GOTO_HOMEPAGE_TITLE',
  CREATE_FIRST_AGREEMENT = 'CREATE_FIRST_AGREEMENT',
  NEW_AGREEMENT = 'NEW_AGREEMENT',
  WELCOME_HEADER = 'WELCOME_HEADER',
  WELCOME_PARAGRAPH = 'WELCOME_PARAGRAPH',
}
