export enum StringBank {
  GROUP_AGREEMENTS = 'GROUP_AGREEMENTS',
  LOGOUT = 'LOGOUT',
  LOGIN_TAGLINE = 'LOGIN_TAGLINE',
  GOTO_HOMEPAGE_TITLE = 'GOTO_HOMEPAGE_TITLE',
  CREATE_FIRST_AGREEMENT = 'CREATE_FIRST_AGREEMENT',
  NEW_AGREEMENT = 'NEW_AGREEMENT',
  WELCOME_HEADER = 'WELCOME_HEADER',
  WELCOME_PARAGRAPH = 'WELCOME_PARAGRAPH',
}
