export enum StringBank {
  LOGIN_TAGLINE = "LOGIN_TAGLINE",
  LOGOUT_BUTTON = "LOGOUT_BUTTON",
  GOTO_HOMEPAGE_TITLE = "GOTO_HOMEPAGE_TITLE",
  CREATE_FIRST_AGREEMENT = "CREATE_FIRST_AGREEMENT",
  NEW_AGREEMENT = "NEW_AGREEMENT"
}
