import { StringBank } from './bank';

export const en: Record<StringBank, string> = {
  ADD_NEW_CATEGORY: 'New Category',
  ADD_RATIONALE_HEADER: 'Add Rationale:',
  ADD_RATIONALE_PARAGRAPH: `Why is this agreement needed? What's the background behind its creation? What needs or problems is it meant to answer?`,
  AGREEMENT_NAME_FIELD: 'Agreement Name',
  AGREEMENT_PARTICIPANTS: '{{count}} participants',
  AGREEMENT_PROCESS_RULES: 'Agreement Process Rules',
  AGREEMENT_APPROVAL_RULES: 'Agreement Approval Rules',
  AGREEMENT_APPROVAL_RULES_DESCRIPTION: 'Set rules for changing agreement status to approved',
  AGREEMENT_PROCESS_RULES_DESCRIPTION:
    'Set rules for accepting changes to the agreement by adding and approving new sections and approving sections improvements suggestions',
  AGREEMENT_PUBLIHSED_SUCCESSFULLY: 'Your agreement has been succesfully published',
  AGREEMENT_UPDATED_AT: 'Updated at: {{date}}',
  ALL_AGREEMENTS: 'All Agreements',
  ARCHIVE: 'Archive',
  ARCHIVE_EMPTY_MESSAGE_FIRST: "And this is where i'll",
  ARCHIVE_EMPTY_MESSAGE_SEC: 'put my archived agreements',
  ARCHIVE_EMPTY_MESSAGE_END: 'If I had any...',
  BACK: 'Back',
  CATEGORY: 'Category',
  CATEGORIES: 'Categories',
  CATEGORY_EMPTY_MESSAGE: "Maybe you'd like to create one",
  COMING_SOON: 'Coming Soon',
  CONTINUE: 'Continue',
  CREATE_FIRST_AGREEMENT: 'Create your first agreement',
  GOTO_HOMEPAGE_TITLE: 'Go to consenz homepage',
  GROUP_AGREEMENTS: "{{group}}'s Agreements",
  CATEGORY_AGREMENTS: '{{category}} category - active Agreements',
  INSERT_NEW_SECTION: '+ Insert new section (Ctrl/Cmd+Enter)',
  LOGOUT: 'Log Out',
  NEW_AGREEMENT: 'New Agreement',
  NEW_CHAPTER: 'New Chapter',
  NO_CATEGORY: 'No Category',
  PUBLISH_AGREEMENT: 'Publish Agreement',
  RATIONALE: 'Rationale',
  REQUIRE_ADMIN_APPROVAL: 'Require Admin Approval',
  REQUIRE_ADMIN_APPROVAL_DESCRIPTION: 'An admin must approve any changes to the draft',
  RETURN_TO_ALL_AGREEMENTS: 'Return to all agreements',
  RULES: 'Rules',
  SECTIONS: 'Sections',
  SHARE_AGREEMENT: 'Share This Agreement',
  TIME_LIMITED_DESCRIPTION: 'For how long the aggremment suggestion will stand for a vote?',
  TIME_LIMITED: 'Time Limited',
  UNARCHIVE: 'Unarchive',
  UNCATEGORIZED: 'General',
  VIEW_AGREEMENT: 'View Agreement',
  WELCOME_HEADER: 'Welcome to consenz!',
  WELCOME_PARAGRAPH: `You are not part of a Group yet,
  ask your Group Manager to invite you to join
  
  and have fun!`,
  SECTION_CARD_TITLE_CHAPTER: '# {{chapterName}}',
  SECTION_CARD_TITLE_SECTIONS: '{{sectionNum}} sections',
  SECTION_CARD_TITLE_SUGGESTIONS: '{{suggestionsNum}} suggestions',
  SECTION_CARD_CONTENT_SECTION_NAME: 'section {{sectionNum}}',
  SECTION_CARD_CONTENT_VERSIONS: 'Version {{versionNum}} of {{totalVersionsNum}}',
};
