import { StringBank } from './bank';

export const en: Record<StringBank, string> = {
  ADD_COMMENT_IN_SECTION: 'Add a comment regarding the section',
  ADD_NEW_CATEGORY: 'New Category',
  ADD_RATIONALE_HEADER: 'Add Rationale:',
  ADD_RATIONALE_PARAGRAPH:
    "Why is this agreement needed? What's the background behind its creation? What needs or problems is it meant to answer?",
  ADD_SECTION: 'Add Section',
  ADD_VERSION: 'Add Version',
  AGREEMENT_APPROVAL_RULES: 'Agreement Approval Rules',
  AGREEMENT_APPROVAL_RULES_DESCRIPTION: 'Set rules for changing agreement status to approved',
  AGREEMENT_LAST_UPDATED: 'Last Updated: {{date}}',
  AGREEMENT_NAME_AND_RATIONALE_REQUIRED: 'Agreement name and rationale are required',
  AGREEMENT_NAME_FIELD: 'Agreement Name',
  AGREEMENT_PARTICIPANTS: '{{count}} participants',
  AGREEMENT_PROCESS_RULES: 'Agreement Process Rules',
  AGREEMENT_PROCESS_RULES_DESCRIPTION:
    'Set rules for accepting changes to the agreement by adding and approving new sections and approving sections improvements versions',
  AGREEMENT_PUBLISHED_SUCCESSFULLY: 'Your agreement has been successfully published',
  AGREEMENT_UPDATED_AT: 'Updated at: {{date}}',
  ALL_AGREEMENTS: 'All Agreements',
  ANONYMOUS: 'Anonymous',
  ARCHIVE: 'Archive',
  ARCHIVE_EMPTY_MESSAGE: "And this is where i'll\nput my archived agreements",
  ARCHIVE_EMPTY_MESSAGE_END: 'If I had any...',
  AT_LEAST_ONE_SECTION_REQUIRED: 'At least one chapter and one section is required',
  BACK: 'Back',
  CANCEL: 'Cancel',
  CATEGORIES: 'Categories',
  CATEGORY: 'Category',
  CATEGORY_AGREEMENTS: '{{category}} category - active Agreements',
  CATEGORY_EMPTY_MESSAGE: "Maybe you'd like to create one",
  COMING_SOON: 'Coming Soon',
  COMMENT_POSTED: 'Comment was posted successfully',
  CONFIRM_COMMENT_DELETE: 'This action will delete the comment. Are you sure?',
  CONFIRM_SECTION_VERSION_DELETE: `This action will delete the section and all of it's comments. This cannot be undone. 
Are you sure?`,
  CONTINUE: 'Continue',
  CREATE: 'Create',
  CREATE_FIRST_AGREEMENT: 'Create your first agreement',
  CURRENT_VERSION: 'Current Version',
  DELETE: 'Delete',
  DELETE_AGREEMENT: 'Delete Agreement',
  DELETE_COMMENT: 'Delete Comment',
  DELETE_SECTION_VERSION: 'Delete This Section Version',
  FEEDBACK: 'Provide Feedback',
  GOTO_HOMEPAGE_TITLE: 'Go to consenz homepage',
  GROUP_AGREEMENTS: "{{group}}'s Agreements",
  INSERT_NEW_SECTION: '+ Insert new section (Ctrl/Cmd+Enter)',
  INSERT_NEW_SECTION_SHORT: 'Insert new section...',
  INSERT_NEW_VERSION: 'Insert new version...',
  LOGOUT: 'Log Out',
  MINIMAL_MAJORITY_FOR_APPROVAL: 'Minimal Majority for Approval',
  MINIMAL_MAJORITY_FOR_APPROVAL_DESCRIPTION:
    'How many supporters will be needed to approve the agreements sections?',
  NEW_AGREEMENT: 'New Agreement',
  NEW_CHAPTER: 'New Chapter',
  NEW_SECTION: 'New Section',
  NO_CATEGORY: 'No Category',
  NO_SECTIONS_PARAGRAPH:
    'Go to the agreement discussion page and vote for the sections that you would like to see here',
  NO_SECTIONS_TITLE: 'No Sections were approved yet.',
  PUBLISH: 'Publish',
  PUBLISH_AGREEMENT: 'Publish Agreement',
  RATIONALE: 'Rationale',
  READ_MORE: 'Read More',
  REMAINING_SUPPORTERS: '{{count}} supporters needed for approval',
  REQUIRE_ADMIN_APPROVAL: 'Require Admin Approval',
  REQUIRE_ADMIN_APPROVAL_DESCRIPTION: 'An admin must approve any changes to the draft',
  REQUIRED_QUORUM: 'Required Quorum',
  REQUIRED_QUORUM_DESCRIPTION:
    'Minimum number of memebers necessary for a the agreement to be approved or denied',
  RETURN_TO_ALL_AGREEMENTS: 'Return to all agreements',
  RULES: 'Rules',
  SECTION: 'Section',
  SECTION_CARD_CONTENT_SECTION_NAME: 'section {{sectionNum}}',
  SECTION_CARD_CONTENT_VERSIONS: 'Version {{versionNum}} of {{totalVersionsNum}}',
  SECTION_CARD_TITLE_CHAPTER: '# {{chapterName}}',
  SECTION_CARD_TITLE_SECTIONS: '{{sectionNum}} sections',
  SECTION_CARD_TITLE_VERSIONS: '{{versionsNum}} versions',
  SECTIONS: 'Sections',
  SHARE_AGREEMENT: 'Share This Agreement',
  TIME_AGO_DAYS_one: 'Yesterday',
  TIME_AGO_DAYS_other: '{{count}} days ago',
  TIME_AGO_HOURS_one: 'An hour ago',
  TIME_AGO_HOURS_other: '{{count}} hours ago',
  TIME_AGO_MINUTES_one: 'A minute ago',
  TIME_AGO_MINUTES_other: '{{count}} minutes ago',
  TIME_AGO_MONTHS_one: 'A month ago',
  TIME_AGO_MONTHS_other: '{{count}} months ago',
  TIME_AGO_SECONDS: 'Just now',
  TIME_AGO_YEARS_one: 'A year ago',
  TIME_AGO_YEARS_other: '{{count}} years ago',
  TIME_LIMITED: 'Time Limited',
  TIME_LIMITED_DESCRIPTION: 'For how long the agreement version will stand for a vote?',
  UNARCHIVE: 'Unarchive',
  UNCATEGORIZED: 'General',
  URL_COPIED_SUCCESSFULLY: 'URL Copied successfully',
  VERSION: 'Version',
  VIEW_AGREEMENT: 'View Agreement',
  VIEW_CURRENT_DRAFT: 'View Current Draft',
  VIEW_DRAFT: 'View Draft',
  WELCOME_HEADER: 'Welcome to consenz!',
  WELCOME_PARAGRAPH:
    'You are not part of a Group yet,\n  ask your Group Manager to invite you to join\n  \n  and have fun!',
};
