import { StringBank } from './bank';

export const en: Record<StringBank, string> = {
  ADD_NEW_CATEGORY: 'New Category',
  ADD_RATIONALE_HEADER: 'Add Rationale:',
  ADD_RATIONALE_PARAGRAPH: `Why is this agreement needed? What's the background behind its creation? What needs or problems is it meant to answer?`,
  ADD_SECTION: 'Add Section',
  ADD_VERSION: 'Add Version',
  AGREEMENT_NAME_FIELD: 'Agreement Name',
  AGREEMENT_PARTICIPANTS: '{{count}} participants',
  AGREEMENT_PROCESS_RULES: 'Agreement Process Rules',
  AGREEMENT_APPROVAL_RULES: 'Agreement Approval Rules',
  AGREEMENT_APPROVAL_RULES_DESCRIPTION: 'Set rules for changing agreement status to approved',
  AGREEMENT_PROCESS_RULES_DESCRIPTION:
    'Set rules for accepting changes to the agreement by adding and approving new sections and approving sections improvements versions',
  AGREEMENT_PUBLIHSED_SUCCESSFULLY: 'Your agreement has been succesfully published',
  AGREEMENT_UPDATED_AT: 'Updated at: {{date}}',
  AGREEMENT_LAST_UPDATED: 'Last Updated: {{date}}',
  ALL_AGREEMENTS: 'All Agreements',
  ANONYMOUS: 'Anonymous',
  ARCHIVE: 'Archive',
  ARCHIVE_EMPTY_MESSAGE: "And this is where i'll\nput my archived agreements",
  ARCHIVE_EMPTY_MESSAGE_END: 'If I had any...',
  BACK: 'Back',
  CANCEL: 'Cancel',
  CATEGORY: 'Category',
  CATEGORIES: 'Categories',
  CATEGORY_EMPTY_MESSAGE: "Maybe you'd like to create one",
  COMING_SOON: 'Coming Soon',
  CONFIRM_COMMENT_DELETE: 'Please write the word "comment"in order to confirm deleting it.',
  CONTINUE: 'Continue',
  CREATE: 'Create',
  CREATE_FIRST_AGREEMENT: 'Create your first agreement',
  CURRENT_VERSION: 'Current Version',
  GOTO_HOMEPAGE_TITLE: 'Go to consenz homepage',
  CATEGORY_AGREMENTS: '{{category}} category - active Agreements',
  DELETE: 'Delete',
  DELETE_AGREEMENT: 'Delete Agreement',
  GROUP_AGREEMENTS: "{{group}}'s Agreements",
  INSERT_NEW_SECTION: '+ Insert new section (Ctrl/Cmd+Enter)',
  INSERT_NEW_SECTION_SHORT: 'Insert new section...',
  INSERT_NEW_VERSION: 'Insert new version...',
  LOGOUT: 'Log Out',
  NEW_AGREEMENT: 'New Agreement',
  NEW_CHAPTER: 'New Chapter',
  NEW_SECTION: 'New Section',
  NO_CATEGORY: 'No Category',
  NO_SECTIONS_TITLE: 'No Sections were approved yet.',
  NO_SECTIONS_PARAGRAPH:
    'Go to the agreement discussion page and vote for the sections that you would like to see here',
  PUBLISH_AGREEMENT: 'Publish Agreement',
  RATIONALE: 'Rationale',
  READ_MORE: 'Read More',
  REMAINING_SUPPORTERS: '{{count}} remaining supporters',
  REQUIRE_ADMIN_APPROVAL: 'Require Admin Approval',
  REQUIRE_ADMIN_APPROVAL_DESCRIPTION: 'An admin must approve any changes to the draft',
  RETURN_TO_ALL_AGREEMENTS: 'Return to all agreements',
  RULES: 'Rules',
  SECTION_CARD_CONTENT_SECTION_NAME: 'section {{sectionNum}}',
  SECTION_CARD_CONTENT_VERSIONS: 'Version {{versionNum}} of {{totalVersionsNum}}',
  SECTION_CARD_TITLE_CHAPTER: '# {{chapterName}}',
  SECTION_CARD_TITLE_SECTIONS: '{{sectionNum}} sections',
  SECTION_CARD_TITLE_VERSIONS: '{{versionsNum}} versions',
  SECTIONS: 'Sections',
  SECTION: 'Section',
  SHARE_AGREEMENT: 'Share This Agreement',
  TIME_LIMITED_DESCRIPTION: 'For how long the aggremment version will stand for a vote?',
  TIME_LIMITED: 'Time Limited',
  UNARCHIVE: 'Unarchive',
  UNCATEGORIZED: 'General',
  URL_COPIED_SUCCESSFULLY: 'URL Copied successfully',
  VERSION: 'Version',
  VIEW_AGREEMENT: 'View Agreement',
  VIEW_CURRENT_DRAFT: 'View Current Draft',
  VIEW_DRAFT: 'View Draft',
  WELCOME_HEADER: 'Welcome to consenz!',
  WELCOME_PARAGRAPH: `You are not part of a Group yet,
  ask your Group Manager to invite you to join
  
  and have fun!`,
};
