import { StringBank } from './bank';

export const he: Partial<Record<StringBank, string>> = {
  ADD_COMMENT_IN_SECTION: 'הוספת הערה על ההצעה הנוכחית',
  ADD_NEW_CATEGORY: 'הוספת קטגוריה',
  ADD_RATIONALE_HEADER: 'דברי הסבר',
  ADD_RATIONALE_PARAGRAPH:
    'למה זקוקים להסכם הזה? מה הרקע ליצירתו? מה אלה הצרכים והבעיות שהוא נועד לספק להם מענה? ...',
  ADD_SECTION: 'הוספת חלק',
  ADD_VERSION: 'הוספת גרסה',
  AGREEMENT_APPROVAL_RULES: 'כללי אישור הסכם',
  AGREEMENT_APPROVAL_RULES_DESCRIPTION: 'הגדירו חוקים עבור שינוי הסכם לסטאטוס "התקבל"',
  AGREEMENT_LAST_UPDATED: 'עדכון אחרון: {{date}}',
  AGREEMENT_NAME_FIELD: 'כותרת ההסכם',
  AGREEMENT_PARTICIPANTS: '{{count}} משתתפים',
  AGREEMENT_PROCESS_RULES: 'כללי יצירת הסכם',
  AGREEMENT_PROCESS_RULES_DESCRIPTION:
    'קבעו חוקים עבור קבלת שינויים להסכם עם הוספת חלקים ואישור גרסהות של חלקים',
  AGREEMENT_PUBLISHED_SUCCESSFULLY: 'ההסכם שלך פורסם בהצלחה',
  AGREEMENT_UPDATED_AT: 'עדכון אחרון: {{date}}',
  ALL_AGREEMENTS: 'כל ההסכמים',
  ANONYMOUS: 'אנונימי',
  ARCHIVE: 'ארכיון',
  ARCHIVE_EMPTY_MESSAGE: 'וכאן זה המקום בו יהיוההסכמים שלנו שבארכיב',
  ARCHIVE_EMPTY_MESSAGE_END: 'אם היו כאלה...',
  BACK: 'חזרה',
  CANCEL: 'ביטול',
  CATEGORIES: 'קטגוריות',
  CATEGORY: 'קטגוריה',
  CATEGORY_AGREEMENTS: 'הסכמים פעילים בקטגוריה {{category}}',
  CATEGORY_EMPTY_MESSAGE: 'אולי תרצו ליצור אחד',
  COMING_SOON: 'מגיע בקרוב',
  COMMENT_POSTED: 'הערה נשלחה בהצלחה',
  CONFIRM_COMMENT_DELETE:
    'מחיקת ההערה הינה פעולה בלתי הפיכה. האם אתם בטוחים שברצונכם למחוק את ההערה?',
  CONFIRM_SECTION_VERSION_DELETE: 'הפעולה המבוקשת תמחוק את ההצעה ואת ההערות שעליה. אתם בטוחים?',
  CONTINUE: 'להמשיך',
  CREATE: 'יצירה',
  CREATE_FIRST_AGREEMENT: 'צרו את ההסכם הראשון שלכם',
  CURRENT_VERSION: 'הגרסה הנוכחית',
  DELETE: 'מחיקה',
  DELETE_AGREEMENT: 'מחיקת הסכם',
  DELETE_COMMENT: 'מחק הערה',
  DEMO: 'זו גרסת הדגמה. אנא התחברו כדי לראות את הגרסה המלאה',
  FEEDBACK: 'העבירו משוב',
  GOTO_HOMEPAGE_TITLE: 'לעבור לדף הבית',
  GROUP_AGREEMENTS: 'ההסכמים של {{group}}',
  INSERT_NEW_SECTION: '+ הוספת חלק חדש (Ctrl/Cmd+Enter)',
  INSERT_NEW_SECTION_SHORT: 'אנא הזינו חלק חדש',
  INSERT_NEW_VERSION: 'אנא הזינו הצעה לסעיף חדש',
  LOGIN: 'התחברות',
  LOGOUT: 'יציאה',
  NEW_AGREEMENT: 'הסכם חדש',
  NEW_CHAPTER: 'פרק חדש',
  NEW_SECTION: 'חלק חדש',
  NO_CATEGORY: 'לא נבחרה קטגוריה',
  NO_SECTIONS_PARAGRAPH: ' עברו לדף הדיון על ההסכם, והצביעו עבור החלק שהייתם רוצים שיוצג כאן',
  NO_SECTIONS_TITLE: 'טרם אושרו חלקים',
  PUBLISH: 'פרסום',
  PUBLISH_AGREEMENT: 'פרסום הסכם',
  RATIONALE: 'דברי הסבר',
  READ_MORE: 'קרא/י עוד',
  REMAINING_SUPPORTERS: 'עוד {{count}} תומכים נדרשים לאישור ההצעה',
  REQUIRE_ADMIN_APPROVAL: 'דורש אישור מנהלים',
  REQUIRE_ADMIN_APPROVAL_DESCRIPTION: 'מנהלים חייבים לאשר שינויים לטיוטא',
  RETURN_TO_ALL_AGREEMENTS: 'חזרה לכלל ההסכמים',
  RULES: 'תנאי ההסכם',
  SECTION: 'סעיף',
  SECTION_CARD_CONTENT_SECTION_NAME: 'סעיף {{sectionNum}}',
  SECTION_CARD_CONTENT_VERSIONS: ' גרסה {{versionNum}} מתוך {{totalVersionsNum}} ',
  SECTION_CARD_TITLE_CHAPTER: '# {{chapterName}}',
  SECTION_CARD_TITLE_SECTIONS: '{{sectionNum}} סעיפים',
  SECTION_CARD_TITLE_VERSIONS: '{{versionsNum}} הצעות',
  SECTIONS: 'חלקים',
  SHARE_AGREEMENT: 'שתפו את ההסכם',
  TIME_LIMITED: 'מוגבל בזמן',
  TIME_LIMITED_DESCRIPTION: 'כמה זמן ההסכם יהיה זמין להצבעה?',
  UNARCHIVE: 'העברה מארכיון',
  UNCATEGORIZED: 'כללי',
  URL_COPIED_SUCCESSFULLY: 'כתובת הועתקה בהצלחה',
  VERSION: 'גרסה',
  VIEW_AGREEMENT: 'צפייה בהסכם',
  VIEW_CURRENT_DRAFT: 'צפייה בגרסה הנוכחית',
  VIEW_DRAFT: 'צפייה בטיוטה',
  WELCOME_HEADER: 'ברוכים הבאים לקונסנז!',
  WELCOME_PARAGRAPH:
    'אתן עוד לא חלק מקבוצה.\n  בקשו ממנהל הקבוצה שלכן הזמנה על מנת להשתתף\n  \n  ותהנו!',
};
