-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "core"."section_versions" add column "threshold" integer
--  not null default '0';
