import styled from "styled-components";
export const FooterButton = styled.button`
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  padding: 12px 16px;
  gap: 10px;
  font-family: "Lato";
  font-style: normal;
  font-weight: 500;
  font-size: 16px;
  line-height: 24px;
  border: 1px solid #828282;
  border-radius: 8px;
  color: #fcfcfd;
  background: rgba(41, 45, 54, 0.5);
  width: 360px;
  height: 48px;
`;
