-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "core"."sections" add column "current_version_id" integer
--  null unique;
